- Cargo.toml
`csv` is only used in the examples
> Move csv to dev-dependencies

- src/de.rs
- tests/test_deserialize.rs
and don't panic on parse error. Adds a `ParsableStringDeserializer` wrapper for Strings to handle primitive deserialization.
> Handle primitive map keys 

- Cargo.toml
- src/de/parse.rs
I just ran into a case where `blah[]=Blah+Blah` included the `+` in the deserialized value. This PR just adds the block responsible for this decoding for `parse_seq_value` (it was already present for `parse_ord_seq_value` and `parse_map_value`).
I also updated the `error-chain` dependency to resolve an `unused_doc_comment`  issue and "fixed" a couple `unused_results`, both of which were preventing me from using the patch locally.
> fix parse_seq_value not decoding '+' to ' '

- examples/introduction.rs
Currently, the example `introduction` fails with:
```
`serde_qs` to_string for map:
user_ids%5B2%5D=3&user_ids%5B0%5D=1&name=Acme&address%5Bpostcode%5D=12345&user_ids%5B3%5D=4&user_ids%5B1%5D=2&phone=12345&id=42&address%5Bcity%5D=Carrot+City
`serde_urlencoded` to_string for map:
user_ids%5B2%5D=3&user_ids%5B0%5D=1&name=Acme&address%5Bpostcode%5D=12345&user_ids%5B3%5D=4&user_ids%5B1%5D=2&phone=12345&id=42&address%5Bcity%5D=Carrot+City
`serde_urlencoded` from_str to pairs:
[("user_ids[2]", "3"), ("user_ids[0]", "1"), ("name", "Acme"), ("address[postcode]", "12345"), ("user_ids[3]", "4"), ("user_ids[1]", "2"), ("phone", "12345"), ("id", "42"), ("address[city]", "Carrot City")]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Custom("missing field `address`"), …
```
> use non-strict parsing to allow round-trip in example

- src/actix.rs
- tests/test_actix.rs
This allows switching to non-strict parsing mode
resolves #21
> Add deserialization parameters to QsQueryConfig

- src/de/parse.rs
- tests/test_deserialize.rs
Hi, I've noticed that `serde_qs`
- fails to parse querystrings starting with an ampersand `&` (e.g. `&foo=bar`), and
- parses something like `a=b&&c=d` as `{ "a": "b", "&c": "d" }`
Those two cases are fixed by this PR. 
If I understand [the spec](https://url.spec.whatwg.org/#urlencoded-parsing) correctly, a `&` at the start, at the end, or an `&&` should be perfectly fine. Those empty byte sequences after splitting by `&` should simply be ignored.
Thanks in advance for considering this change!
> Fix deserializing empty sequences

- Cargo.toml
- src/error.rs
- src/lib.rs
- src/ser.rs
thiserror provides a simpler interface than error-chain, directly
generating an error enum similar to what could be written by hand. It
also reduces dependencies; error-chain pulls in backtrace which
currently pulls in gimli, which is fairly heavyweight.
This changes the error type's interface, so it'll require a bump to
0.7.0.
> Switch from error-chain to thiserror

- src/de/mod.rs
- src/ser.rs
- tests/test_deserialize.rs
- tests/test_serialize.rs
Closes #36 
I also wrote the tests covering these changes, but didn't change the documentations.
> Support enum unit variants as map keys

- Cargo.toml
- src/lib.rs
- src/warp.rs
- tests/test_warp.rs
Adds support for the warp framework
Having to add the `.recover()` function is unintuitive but I'm not aware of a better solution  
However, the recover function is not *strictly* necessary. It turns the `Rejection`, which would result in a `500 Internal Server Error`, into a `400 Bad Request`
> Add warp support

- src/ser.rs
- tests/test_serialize.rs
This PR fixes issue #45 by ensuring that keys go through same encoding steps as values.
> Fixes #45 - encoding not working correctly on maps

- src/de/parse.rs
- src/lib.rs
- tests/test_deserialize.rs
> feat: non-strict mode replaces invalid UTF-8

- src/axum.rs
QsQuery's FromRequest implementation expects a plain QsQueryConfig
extension, i.e., not an Arc.
> Fix QsQueryConfig example

- src/lib.rs
The API of `serde_with` changed with the release of its version 2.0.0. 
This PR update the `flatten` issue workaround accordingly to the new API.
> Update flatten issue workaround for serde_with 2.0.0

- src/de/mod.rs
- src/ser.rs
- tests/test_deserialize.rs
- tests/test_serialize.rs
This adds serializing and deserializing support for the following top level types:
```rust
()
struct A;
```
Fixes #72
> Improve support unit types

- Cargo.toml
- examples/csv_vectors.rs
This PR adds a test for the mentioned example because it suffered from the bit rot and currently doesn't work:
```bash
> cargo r -q --example csv_vectors
Query { r: [], s: 12 }
```
> Add test for `csv_vectors` example

- src/de/mod.rs
- src/lib.rs
We use `serde_qs` for a custom `DeserializeSeed`.
`ValueDeserializer` is my Deserializer. 
```rs
let input = "title=Hello";
// ValueDeserializer is a custom DeserializeSeed
let deserializer = ValueDeserializer::new();
let de = serde_qs::Deserializer::new(input.as_bytes()).expect("parse QueryString failed");
let value = deserializer.deserialize(de).expect("parse QueryString failed");
```
This PR just make `QsDeserializer` pub as `Deserializer` and add a `new` method to create a Deserializer.
Like serde_yaml and serde_json:
- https://docs.rs/serde_yaml/latest/serde_yaml/struct.Deserializer.html
- https://docs.rs/serde_json/latest/serde_json/struct.Deserializer.html#method.from_str
> Add `Deserializer::new` to crate a new deserializer, and public deserializer.

- Cargo.toml
`axum` support is missing from docs.rs. This enables it in addition to `actix` and `warp`.
> docs.rs: generate docs for axum support as well

- CHANGELOG.md
- Cargo.toml
* `serde_qs`: 0.13.0 -> 0.14.0 (✓ API compatible changes)
<details><summary><i><b>Changelog</b></i></summary><p>
<blockquote>
- Add release plz CI ([#125](https://github.com/samscott89/serde_qs/pull/125))
- Update CI config ([#124](https://github.com/samscott89/serde_qs/pull/124))
- update axum to v0.8 ([#118](https://github.com/samscott89/serde_qs/pull/118))
- :multiple_bound_locations ([#103](https://github.com/samscott89/serde_qs/pull/103))
- Add axum::OptionalQsQuery ([#102](https://github.com/samscott89/serde_qs/pull/102))
- generate docs for axum support as well ([#100](https://github.com/samscott89/serde_qs/pull/100))
- Update README.md
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/release-plz/release-plz/).
> chore: release v0.14.0

- src/de/mod.rs
- src/de/parse.rs
- tests/test_deserialize.rs
Fixes #127 
This pr respects serde's struct deserialize ordering when deserializing struct values which has the effect of mitigating buffering in some cases.
> reorder struct fields to avoid serde buffering

- .github/workflows/ci.yml
- Cargo.toml
- src/de/mod.rs
- src/de/parse.rs
- src/lib.rs
- tests/test_deserialize.rs
Dear samscott89,
Please consider this pull request.
This PR adds support for deserializing queries into ordered maps, such as `IndexMap`.
It adds a new feature, called `indexmap`, that replaces the `BTreeMap` used internall by `serd_qs` with an `IndexMap`.
Sometimes the order of the keys in the query is important. On example is sorting. What if you want to sort by one field, and then by other?
There's a new test. It parses a two queries into a map. The queries are almost the same, but the order of the keys is swapped.
> Support preserving order of parameters when serializing to a Map.

- CHANGELOG.md
- Cargo.toml
* `serde_qs`: 1.0.0-rc.0 -> 1.0.0-rc.1 (✓ API compatible changes)
<details><summary><i><b>Changelog</b></i></summary><p>
<blockquote>
- Fix maps with integer keys. ([#138](https://github.com/samscott89/serde_qs/pull/138))
- Support explicit serialization formatting for arrays. ([#137](https://github.com/samscott89/serde_qs/pull/137))
- v1 changelog (and more tests) ([#135](https://github.com/samscott89/serde_qs/pull/135))
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/release-plz/release-plz/).
> chore: release v1.0.0-rc.1

- CHANGELOG.md
- Cargo.toml
* `serde_qs`: 1.0.0-rc.1 -> 1.0.0-rc.2 (✓ API compatible changes)
<details><summary><i><b>Changelog</b></i></summary><p>
<blockquote>
- A little cleanup in web utils ([#140](https://github.com/samscott89/serde_qs/pull/140))
- Sam/more tests ([#139](https://github.com/samscott89/serde_qs/pull/139))
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/release-plz/release-plz/).
> chore: release v1.0.0-rc.2
